cmake_minimum_required (VERSION 3.6)

list(APPEND CMSISDSP_SOURCES
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_init_f32.c
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_init_q15.c
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_init_q31.c
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_reset_f32.c
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_reset_q15.c
	${CMAKE_CURRENT_LIST_DIR}/arm_pid_reset_q31.c
)

if (NOT CONFIGTABLE OR ALLFAST OR ARM_SIN_COS_F32)
	list(APPEND CMSISDSP_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arm_sin_cos_f32.c)
endif()

if (NOT CONFIGTABLE OR ALLFAST OR ARM_SIN_COS_Q31)
	list(APPEND CMSISDSP_SOURCES ${CMAKE_CURRENT_LIST_DIR}/arm_sin_cos_q31.c)
endif()
